### PR TITLE
check it out

### PR DESCRIPTION
**Pull request by torkildjensen**

### CODE REVIEW

**Comment by evowilliamson** [comment]
If you want to contribute, I will make a separate branch for it. But at the moment I don't have a clear roadmap. Are you just testing or are you interested in helping out ?

**Comment by torkildjensen** [comment]
Sure. I went through the code and I want to perform some simple work. I am not very experienced programmer, but would like to learn. What can I do?

**Comment by torkildjensen** [comment]
Nice! I just created a branch: 1.02-vis-sccs. Take a look at the project board, there is an activity. You can pick up that story. There is not a lot of documentation, so you might get lost in the beginning. Just take the test cases as a lead and you can get up and running fast. 

Thanks again for your interest!

**Comment by evowilliamson** [comment]
NIce! I created an activity 1.02-vis-sccs. Check the project board. There is not a lot of docs around, so take a look at the testcases. If you need some help, just let me know.

Thanks again for your interest!

**Pull request closed without merging**
